<?php

return [
    'access' => [
        'category'=>[
            'list-category'=>'category_List',
            'add-category'=>'category_Add',
            'edit-category'=>'category_Edit',
            'delete-category'=>'category_Delete',
        ],
        'product'=>[
            'list-product'=>'products_List',
            'add-product'=>'products_Add',
            'edit-product'=>'products_Edit',
            'delete-product'=>'products_Delete',
        ],
        'slider'=>[
            'list-slider'=>'slider_List',
            'add-slider'=>'slider_Add',
            'edit-slider'=>'slider_Edit',
            'delete-slider'=>'slider_Delete',
        ],
        'settings'=>[
            'list-settings'=>'setting_List',
            'add-settings'=>'setting_Add',
            'edit-settings'=>'setting_Edit',
            'delete-settings'=>'setting_Delete',
        ],
        'user_list'=>[
            'list-user'=>'user_List',
            'edit-user'=>'user_Edit',
            'delete-user'=>'user_Delete',
        ],
        'role'=>[
            'list-role'=>'role_List',
            'add-role'=>'role_Add',
            'edit-role'=>'role_Edit',
            'delete-role'=>'role_Delete',
        ],
        'permission'=>[
            'add-permission'=>'permission_Add',
        ],
        'customer'=>[
            'list-customer'=>'customer_List',
        ],
        'orders'=>[
            'list-orders'=>'orders_List',
            'edit-orders'=>'orders_Edit',
        ],



    ],
    'table_module'=>[
        'category',
        'products',
        'slider',
        'setting',
        'user',
        'role',
        'permission',
        'customer',
        'orders',
    ],
    'module_childrent'=>[
        'List',
        'Add',
        'Edit',
        'Delete'
    ]
];
